ASSIGNMENT=wp1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
#ASSIGNMENT=wp3
#ASSIGNMENT=project
TEAM_MEMBERS_CSV="Shashwat Arghode, Pratibha Pandey"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative signals
PROJECT_POINTS=50
